language: node_js
node_js: 10.16
before-install:
- openssl aes-256-cbc -K $encrypted_dfdcfd5172af_key -iv $encrypted_dfdcfd5172af_iv
  -in deploy_key.enc -out ./deploy_key -d  
- cd APIgateway
install:
- npm install
script:
- echo "test api_gateway"
after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker build -t orenda15/api_gateway:$TRAVIS_COMMIT .
- docker push orenda15/api_gateway:$TRAVIS_COMMIT
- chmod 600 ../deploy_key && ssh -o StrictHostKeyChecking=no -i ../deploy_key ubuntu@149.165.170.101 "~/deployFiles/deployApi.sh $TRAVIS_COMMIT"

branches:
  only:
  - deployApi
env:
  global:
  - secure: PjQw1TFLJqMQjjSill+zCcAe9Hsd0s/+xeCcsHfrcFiNHm3SfmPIEsS8g7s/XrS/zquXA8NFKUoDhLO7SRQjnSVVFFmPHFcOzQdSs9IgovS2ykuB0gtp/4EXFPA+xLAW2vq0s6ESjTj6Bbx5xQHiHKrHkQqZZhoS9C/ZgNk9yiAtQUDOLjb70+jysa50bUwPFhyqjs0iyWKuZ77Y0hkdo6Xde0m8otEpiD09rHWFzR9J1DISQfGtWpFYcaQzQPP2YtJ/jKsT0chJDNJEcSu2tz9TlJQb5yAnlnaDEHF53rQ4/Y9hrjDdVJFB5mNrNoHyVwDkDMY82Cl4BkKpZOhxCtd/zX63kDloLy1Ymm92Z03j9tAd7S+UunfzVCY98S5+8zy/80bNGr5sxyUZCXjFRU2KrSiBPt5pq7AXoz2Xdf8S1mB85315oTwG3k2vzDc20e2JjcHNtodggfJMUh5WLljuj0QBSdX9K/MUIfmkNxmtwvOicIRDVQ0MtNHLuttC7bbh/RSFbhaj+2DoHKLPXYeZi4GpmLrpOsdrgNhmCPxp9xS2ghlDe/6KLtxkq6ovnk3HaUaIWZwv3ucAfAzqh0/8GzVHi+wxGQ9ZcMCxQGcLuyGbD7cutG7iBHEZMO8CyMFfEzIEpQ6ICTaPiOaGqmXKQt6rRJFMMBr0has2wkA=
  - secure: kKFKwxqKPs/wCv5Chfj7+Ofjt8NJjgAP2U6SyrYQuczaDZtDX4/C7dDi6tLvKGB4rBhViGKfO8WtaiX5NNG+AwqkhRhXCEk2Fn0aF1uDOqKbjOsqcl0zCWtusoLuQF/itl8EgnkGisBTANz0aF9LpV9f+lIJeKnjLe3COjaqQwCDu6uFMHWB6h/Mi19KJsstKeqoVd1ISAvsIq2bn3bNSrupN8iE4LJY6XnNU2Frr8qKbSJ6p6ftOuUymyalJpgHODQph1BYtU/SKYqcOFuglFnJt3hu5xYjSJJ3UyfNtPYgEYDMR1IJUkt+HFT2ofuR8gAFSolbUNMGJ775xUYvhTm/i/pjcH2a2FE07+j4Zuq+WsWtBY+hrIf5KZ8FZ469UKVvjgF8sdKflhjiEc6R118b9DrFsWMZlT/c0iIextzVP1PfV5W9HAvxNZdqoO10wngUoyGaJgoCu9NPRXWyajTwz0cEW48yFgx+A+Y9GEChaYbMn1qZluePVWSli1wAlcuUX9xeXgNOXnAUkO579TXGBYl/XBM5Ae9BboeZNdF3komf7IUcTvn4e+HuSi+OfOLE6IQT429Iea34lisY69aj8kUP0/7mVSAWI5NWO2150dDTwK/dQ7tOr2WFj+zpN41bTWn8hjo1VtGej68L/gs1VneI8FXS1NhwIgM5dGc=
  - secure: Wasmtf+PURPA5qEo5PlymB/MuAG/sADzB9WdougCK+JZTvMK0b9wRYUaJh+9OGvQNhxQ0JACAIk49rGc15eV4r5sX5PAKPLUeUStswx5d6sa2Zgw6+lKfgWqzSb1lvAOnJaZ6AyCpvEgDhN2CZv44yvR0U+JEykR40iQcYvLNqRh8nfOKVlPXUoOAt8zz+QsWcH2JxnLGEChFIphtk84efai0kfKEQNlvlxZm9qtnwDrSnNd/+UKRgSrGpEj6L7l07VWcocSPYUc6CXFLk5/W+697FOzO8acmLM94s69SQxfwdtxTsbQzCwe30iHFWS+qqlcweawsFjo49ePbA+PTV6MxWcwYK20SEUDyY+7ACiFnQA0wnqTVKPfz8TWKj0jPLX3uV2dJ2wwL/ODJ7PdT6vQ5uYty6DPCbBK8URU7K7eneBQfFeaslgHlDk8WnqJM0L0DrlbnK49Xze5exuNXrJc2iVLXiNIr2GPKun+WDv2s+AFqHqIQwA8+LvK7+2eDrP35ibWkxL15WjrhrK8+vYC7rPU2KIzmhLjMsMh5QpIrVKNDUwLCzNafVAGyMrQf9MhA8PcjtelOBcL0YbcDCMXdpP/cFrcJUeij/V8L6CwGZaILmz/9QgzR2A2GY/q3G84OZaUY6OiEFJi2pER3cqMRK3feTaktS14xyXGfx4=
