---
kind: Service
apiVersion: v1
metadata:
  name: usermanagementservice
spec:
  selector:
    app: user-management
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3003
      # Port to forward to inside the pod
      targetPort: 5009
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
 
 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: user-management-deployment
spec:
  selector:
    matchLabels:
      app: user-management
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: orenda15/user_management:latest
        ports:
        - containerPort: 5009

